- hosts: localhost
  vars:
    - config: "{{ playbook_dir }}/{{ oneview_config }}"
    - server_profile_template_name: '' 
    - server_profile_name: TestProfile
    - server_hardware_name: ""
    - ilo_ip_address: ""
    - session: ""
  tasks:
    - name: Fetch Server hardware type of Server profile template
      oneview_server_profile_template_facts:
        config: "{{ config }}"
        name: "{{ server_profile_template_name }}"
      delegate_to: localhost

    - name: Gather server hardware having no profiles
      oneview_server_hardware_facts:
        config: "{{ config }}"
        params:
          filter: 
            - serverProfileUri=null
            - serverHardwareTypeUri='{{ server_profile_templates[0].serverHardwareTypeUri }}'
            - status='OK'
      when: server_profile_templates|length > 0 
      delegate_to: localhost  
     
    - set_fact: 
        server_hardware_name: "{{ server_hardwares[0].name }}"
      when: server_hardwares|length > 0
#    - set_fact:
#        server_hardware_name_split: "{{ server_hardware_name.split(',') }}"
#      when: server_hardwares|length > 0
#    - set_fact:
#        bay_name: "{{ server_hardware_name_split[1] }}"
#      when: server_hardwares|length > 0
#    - set_fact:
#        server_profile_name: "{{ ( server_profile_name + bay_name )}}"
#      when: server_hardwares|length > 0
    #- debug:
    #    msg: '{{ server_profile_name }}'

    - name: Create server profile from template
      oneview_server_profile:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ server_profile_name }}"
          serverProfileTemplateName: "{{ server_profile_template_name }}"
          serverHardwareName: "{{ server_hardware_name }}"
      when: server_hardware_name != "" 
      delegate_to: localhost
    - debug: var=server_profile

    - name: Gather facts about a Server Profile by name
      oneview_server_profile_facts:
        config: "{{ config }}"
        name: "{{server_profile_name}}"
      delegate_to: localhost

    - debug: var=server_profiles

    - set_fact:
        mac_addresses: "{{ server_profiles[0].connectionSettings.connections | map(attribute='mac') | list }}"

    - debug:
        msg: "{{ mac_addresses }}"
