- hosts: localhost
  vars:
    - server_profile_name: ''
    - config: "{{ playbook_dir }}/{{ oneview_config }}"
    - mode: 'UEFI'                    #default is UEFI
    - pxe_boot_policy: 'Auto'         #default set to Auto
    - manage_mode: true               #deault is true
  tasks:
    - name: Gather facts about a Server Profile by name
      oneview_server_profile_facts:
        config: "{{ config }}"
        name: "{{server_profile_name}}"
      delegate_to: localhost

    - debug:
        var: server_profiles
    - debug:
        msg: "Server profile not found kindly check server profile name"
      when: server_profiles|length == 0 and server_profiles[0].name != server_profile_name
    - meta: end_play
      when: server_profiles|length == 0 and server_profiles[0].name != server_profile_name

    - set_fact:
        server_profile_uri: '{{ server_profiles[0].uri }}'
      when: server_profiles|length > 0

    - debug:
        msg: '{{ server_profile_uri }}'

    - name: Gather facts about all Server Hardwares
      oneview_server_hardware_facts:
        config: "{{ config }}"
        params:
          filter:
            - serverProfileUri='{{ server_profile_uri }}'
      delegate_to: localhost

    - debug:
        var: server_hardwares

    - set_fact:
        server_hardware_name: '{{ server_hardwares[0].name }}'
      when: server_hardwares|length > 0

    - debug:
        msg: '{{ server_hardware_name }}'
    - name: Power Off the server hardware
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : '{{ server_hardware_name }}'
            powerStateData:
                powerState: "Off"
                powerControl: "MomentaryPress"
      delegate_to: localhost
    - name: Update bootMode from recently created
      oneview_server_profile:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ server_profile_name }}"
          bootMode:
            manageMode: "{{ manage_mode }}"
            mode: "{{ mode }}" 
            pxeBootPolicy: "{{ pxe_boot_policy }}"
        params:
          force: True # Supprted only for API version >= 600
      delegate_to: localhost

    - name: Power On the server hardware
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : '{{ server_hardware_name }}'
            powerStateData:
                powerState: "On"
                powerControl: "MomentaryPress"
      delegate_to: localhost
